### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

### ISSUE THREAD

**Issue by HeckerMan123** [pytest-dev/pytest-cov#483]
Im trying to download StormBreaker and this error pops up evry time i try to use the command "sudo python3 Storm-Breaker.py":
Traceback (most recent call last):
  File "/home/kali/Storm-Breaker/Storm-Breaker.py", line 36, in <module>
    banner.banner()
  File "/home/kali/Storm-Breaker/modules/banner.py", line 10, in banner
    Popen('neofetch')
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'
I have no idea what to do and i am new to linux so i dont really know much about it.

**Comment by Kushan7** [comment]
Use this command to install neofetch `sudo apt install neofetch`
The error will be solved :+1:

**Comment by Tsotne1998** [comment]
@Kushan7  i used that command and i got this E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. can u help me?

**Comment by Kushan7** [comment]
> @Kushan7 i used that command and i got this E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. can u help me?

so did  `'sudo dpkg --configure -a'` this worked for you? if not what error did it showed up

**Comment by deeq21** [comment]
I need help please
