### ISSUE TITLE
Hangs when using multiprocessing Pool and map

### ISSUE THREAD

**Issue by eytanadler** [pytest-dev/pytest-cov#521]
# Summary

pytest-cov hangs when using multiprocessing Pool and map. I've seen previous issues opened about this (might relate to #520?), but as far as I know the same problem has not been reported. I've created a minimal example (see the code below).

I am using the multiprocessing syntax (using the `with` block) laid out on [this page](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#if-you-use-multiprocessing-pool).

Thanks in advance for any help!

## Expected vs actual result

I expect a coverage file output, but running `python -m pytest --cov` results in the test hanging. Running `python -m pytest` works as expected, with the test passing and properly exiting.

# Reproducer

## Versions

Running on Ubuntu 20.04.3 LTS

```
Package    Version
---------- -------
attrs      21.4.0
coverage   6.3
iniconfig  1.1.1
packaging  21.3
pip        21.2.4
pluggy     1.0.0
py         1.11.0
pyparsing  3.0.7
pytest     6.2.5
pytest-cov 3.0.0
setuptools 58.0.4
toml       0.10.2
wheel      0.37.1
```

```
Python 3.10.0 (default, Dec 21 2021, 13:36:04) [GCC 7.5.0] on linux
```

I'm seeing the same problem on Python 3.8.12 as well.

## Config

I am using the following `.coveragerc` file to avoid covering the test:

```
[run]
omit=test_calc.py
```

## Code

I have created a minimal example to show the bug. In the directory I have three files:
1. `.coveragerc`: listed above
2. `calc.py`: a very simple function that uses the multiprocessing library to square a list of numbers
3. `test_calc.py`: contains a single test to test the `par_calc` function in `calc.py`

### `calc.py`
```python
import multiprocessing

def par_calc(n):
    """
    Squares a list of numbers (0 to n-1)
    """
    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    # Initialize the parallel pool and compute the OpenAeroStruct data
    with multiprocessing.Pool() as parallel_pool:
        out = list(parallel_pool.map(calc, list(range(n))))
    
    return out

def calc(x):
    y = x*x
    return y
```

### `test_calc.py`
```python
import unittest
from calc import par_calc

class ParallelTestCase(unittest.TestCase):
    def test_par_calc(self):
        correct = [0, 1, 4, 9, 16]
        result = par_calc(5)

        for i, val in enumerate(correct):
            self.assertEqual(val, result[i])
```

### Commands run

The commands are run in the root directory that contains the three files described above.

`python -m pytest` works fine:

```
========================================== test session starts ==========================================
platform linux -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/eytan/Documents/test
plugins: cov-3.0.0
collected 1 item                                                                                        

test_calc.py .                                                                                    [100%]

=========================================== 1 passed in 0.04s ===========================================
```

`python -m pytest --cov` hangs here:

```
========================================== test session starts ==========================================
platform linux -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/eytan/Documents/test
plugins: cov-3.0.0
collected 1 item                                                                                        

test_calc.py 
```

When I kill the test while it's hanging I get the following output:

```
========================================== test session starts ==========================================
platform linux -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/eytan/Documents/test
plugins: cov-3.0.0
collected 1 item                                                                                        

test_calc.py ^CTraceback (most recent call last):
Traceback (most recent call last):
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
    _run_finalizers(0)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/pytest_cov/embed.py", line 99, in cleanup
    _cleanup(_active_cov)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/pytest_cov/embed.py", line 85, in _cleanup
    cov.save()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 697, in save
    data = self.get_data()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 766, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/collector.py", line 473, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
    _run_finalizers(0)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 236, in _wrapped
    return method(self, *args, **kwargs)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 459, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 518, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/pytest_cov/embed.py", line 99, in cleanup
    _cleanup(_active_cov)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 313, in _connect
    self._open_db()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/pytest_cov/embed.py", line 85, in _cleanup
    cov.save()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 264, in _open_db
    self._read_db()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 697, in save
    data = self.get_data()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 268, in _read_db
    with self._dbs[threading.get_ident()] as db:
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 766, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 1073, in __enter__
    self._connect()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/collector.py", line 473, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 1041, in _connect
    if self.con is not None:
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 236, in _wrapped
    return method(self, *args, **kwargs)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 605, in _on_sigterm
    self._atexit("sigterm")
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 459, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 601, in _atexit
    self.save()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 518, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 697, in save
    data = self.get_data()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 313, in _connect
    self._open_db()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 766, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 264, in _open_db
    self._read_db()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/collector.py", line 473, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 268, in _read_db
    with self._dbs[threading.get_ident()] as db:
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 234, in _wrapped
    with self._lock:
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 1073, in __enter__
    self._connect()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 1052, in _connect
    self.con = sqlite3.connect(self.filename, check_same_thread=False)
KeyboardInterrupt
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 605, in _on_sigterm
    self._atexit("sigterm")
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 601, in _atexit
    self.save()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 697, in save
    data = self.get_data()
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/control.py", line 766, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/collector.py", line 473, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/eytan/miniconda3/envs/test_debug/lib/python3.10/site-packages/coverage/sqldata.py", line 234, in _wrapped
    with self._lock:
KeyboardInterrupt


---------- coverage: platform linux, python 3.10.0-final-0 -----------
Name      Stmts   Miss  Cover
-----------------------------
calc.py      13      3    77%
-----------------------------
TOTAL        13      3    77%


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/eytan/miniconda3/envs/test_debug/lib/python3.10/multiprocessing/popen_fork.py:27: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
=================================== no tests ran in 94.74s (0:01:34) ====================================
```

**Comment by ionelmc** [comment]
cleanup_on_sigterm is not supported since python 3.8 (installing sigterm handlers is known to mess up multiprocessing).

If you care about this problem push for it [here](https://bugs.python.org/issue38227) or one of the related issues.

**Comment by eytanadler** [comment]
Though I was running into this problem on Python 3.10.0
