### ISSUE TITLE
RecursionError: maximum recursion depth exceeded with --cov-report=html

### ISSUE THREAD

**Issue by npow** [pytest-dev/pytest-cov#529]

**Comment by rakeshrathod1809** [comment]
I also have same issue while generating HTML coverage report. XML is working fine. Please check the issue.

**Comment by nedbat** [comment]
Can either of you provide a reproducible case? 

@rakeshrathod1809 I don't understand how adding the `-d` option to the html command could have an effect.  Can you provide the full error report you are seeing?

**Comment by ionelmc** [comment]
@npow it would appear that you have https://github.com/gabrielfalcao/sure installed but it's not in the package list. Does this problem reproduce with either assertion rewriting disabled (`--assert=plain`) or `sure` uninstalled?

**Comment by rakeshrathod1809** [comment]
@nedbat 
I am having issue with `pytest tests --cov=app --cov-report=html`.
Regarding `coverage html -d coverage_html`, I am using it as an alternative to generate HTML reports from the `.coverage` file generated by `pytest`. And it's working properly. I have mentioned it just for reference.

Please find the error report below.
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\_pytest\main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\_pytest\main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\pytest_cov\plugin.py", line 303, in pytest_runtestloop
INTERNALERROR>     self.cov_total = self.cov_controller.summary(self.cov_report)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\pytest_cov\engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\pytest_cov\engine.py", line 189, in summary
INTERNALERROR>     total = self.cov.html_report(ignore_errors=True, directory=output)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\control.py", line 1028, in html_report
INTERNALERROR>     ret = reporter.report(morfs)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\html.py", line 205, in report
INTERNALERROR>     self.incr.check_global_data(self.config, self.pyfile_html_source)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\html.py", line 447, in check_global_data
INTERNALERROR>     m.update(d)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\misc.py", line 255, in update
INTERNALERROR>     self.update(a)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\misc.py", line 255, in update
INTERNALERROR>     self.update(a)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\misc.py", line 255, in update
INTERNALERROR>     self.update(a)
INTERNALERROR>   [Previous line repeated 964 more times]
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\coverage\misc.py", line 251, in update
INTERNALERROR>     a = getattr(v, k)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\sure\__init__.py", line 1104, in method
INTERNALERROR>     builder = AssertionBuilder(name, negative=is_negative)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\sure\__init__.py", line 483, in __init__
INTERNALERROR>     self._that = AssertionHelper(self.obj)
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\sure\old.py", line 91, in __init__
INTERNALERROR>     if all_integers(within_range):
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\sure\old.py", line 57, in all_integers
INTERNALERROR>     if not is_iterable(obj):
INTERNALERROR>   File "E:\Projects\AWS_Demo\homek-alexa-lambda\.venv\lib\site-packages\sure\old.py", line 53, in is_iterable
INTERNALERROR>     return hasattr(obj, '__iter__') and not isinstance(obj, string_types)
INTERNALERROR> RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by rakeshrathod1809** [comment]
@ionelmc and @nedbat 
One more observation based on comment of @ionelmc. I have just commented `sure` in my code and it's working properly. With `sure`, there is issue.
