### ISSUE TITLE
INTERNALERROR> SystemError: AST constructor recursion depth mismatch (before=78, after=133)

### ISSUE THREAD

**Issue by coneybeare** [pytest-dev/pytest-cov#606]
# Summary

We are seeing a very weird error in which coverage runs with html outputs are raising this `INTERNALERROR`

executed command and options:

```
pytest --cov app/ --cov-report term-missing --cov-report html:coverage --cov-branch --cov-append -vv
```

Error traceback
```
INTERNALERROR> Traceback (most recent call last):00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/_pytest/main.py", line 270, in wrap_session00:14
INTERNALERROR>     session.exitstatus = doit(config, session) or 000:14
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/_pytest/main.py", line 324, in _main00:14
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_hooks.py", line 433, in __call__00:14
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)00:14
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 112, in _hookexec00:14
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)00:14
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pluggy/_callers.py", line 133, in _multicall00:14
INTERNALERROR>     teardown[0].send(outcome)00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py", line 307, in pytest_runtestloop00:14
INTERNALERROR>     self.cov_total = self.cov_controller.summary(self.cov_report)00:14
INTERNALERROR>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper00:14
INTERNALERROR>     return meth(self, *args, **kwargs)00:14
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/pytest_cov/engine.py", line 189, in summary00:14
INTERNALERROR>     total = self.cov.html_report(ignore_errors=True, directory=output)00:14
INTERNALERROR>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/coverage/control.py", line 1157, in html_report00:14
INTERNALERROR>     ret = reporter.report(morfs)00:14
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/coverage/html.py", line 313, in report00:14
INTERNALERROR>     self.write_html_file(ftr, prev_html, next_html)00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/coverage/html.py", line 388, in write_html_file00:14
 00:14
INTERNALERROR>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/coverage/html.py", line 130, in data_for_file00:14
INTERNALERROR>     for lineno, tokens in enumerate(fr.source_token_lines(), start=1):00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/coverage/phystokens.py", line 120, in source_token_lines00:14
INTERNALERROR>     match_case_lines = MatchCaseFinder(source).match_case_lines00:14
INTERNALERROR>                        ^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/site-packages/coverage/phystokens.py", line 85, in __init__00:14
INTERNALERROR>     self.visit(ast.parse(source))00:14
INTERNALERROR>                ^^^^^^^^^^^^^^^^^00:14
INTERNALERROR>   File "/usr/local/lib/python3.11/ast.py", line 50, in parse00:14
INTERNALERROR>     return compile(source, filename, mode, flags,00:14
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00:14
INTERNALERROR> SystemError: AST constructor recursion depth mismatch (before=78, after=133)
```

We also cannot reproduce locally, only on CI (semaphore), very strange.

## Expected vs actual result

I would expect the coverage not to raise this error. However I am not entirely convinced it is a bug, and not a config issue. Please educate me.

# Reproducer

## Versions

Output of relevant packages `pip list`, `python --version`, `pytest --version` etc.

```
pytest==7.4.0
pytest-cov==4.1.0
```

```
% python --version
Python 3.11.3
```

Make sure you include complete output of `tox` if you use it (it will show versions of various things).

## Config

Include your `tox.ini`, `pytest.ini`, `.coveragerc`, `setup.cfg` or any relevant configuration.

## Code

Link to your repository, gist, pastebin or just paste raw code that illustrates the issue.

If you paste raw code make sure you quote it, eg:

```python
def foobar():
    pass
```

**Comment by coneybeare** [comment]
We have isolated it comes from the `--cov-report html:coverage` as the error is not raised when that option is omitted.

**Comment by coneybeare** [comment]
And it seems to have to do with `match_case_lines` and code that uses it? We only have one place in this code for that

```
        match action:
            case foo.CREATED:
                do_something
            case foo.BLAH:
                pass
            case _:
                do_something_else
```

**Comment by nedbat** [comment]
This is weird.  Any chance you can share the actual code? What version of coverage do you have installed?  About the CI, can you check the precise versions of Python and the packages you are using?

**Comment by dpritchett-rebellion** [comment]
We're seeing this same exception despite not using the code coverage reporter. I managed to work around it by telling pytest to use a less-aggressive traceback format: `pytest --tb=line` gets me shorter output on failures but at least it doesn't hang up in the AST recursion wilderness.

Notes on `--tb` options: https://docs.pytest.org/en/7.1.x/how-to/output.html

**Comment by coneybeare** [comment]
Nice find, this worked for me as a workaround too

**Comment by wbloos** [comment]
@dpritchett-rebellion should this issue be moved to the main project to get the attention it needs?

**Comment by Andrew-Brock** [comment]
I was facing this same error too with PyTest on Python 3.11.7. The exact same PyTest version and test suite on Python versions 3.8, 3.9 & 3.10 did not have this issue. I am using pytest-cov, but disabling it did not seem to help.

For me, adding `--tb=native` (see [documentation](https://docs.pytest.org/en/7.1.x/how-to/output.html)) made the error go away and also still means I get callstacks for any failures as opposed to the previously suggested `--tb=line`.

I spent some time trying to figure out what the actual problem was and trying different combinations, but didn't want to spend too much time.
A few observations I did make though:
* `--tb=line` did not seem to help my situation. It meant that PyTest didn't crash and abort in the middle of my test suite, but it was still encountering a bogus failure with `SystemError: AST constructor recursion depth mismatch (before=174, after=210)` in the middle of 1 of my tests and hence making it fail.
* `--tb=native` is not creating bogus failures in my tests
* Despite running the exact same container with all of the same Python, dependencies, etc. in Docker for Windows (in WLS2 mode) and on Ubuntu, it was only failing in Ubuntu. My git is configured to always check out with LF line endings so in theory this should be identical between WIndows & Linux but there must be something different. I was also not able to reproduce it locally on Windows outside of Docker either, despite also having the exact same Python 3.11.7 & requirements installed.
