### ISSUE TITLE
pkg_resources.VersionConflict 

### ISSUE THREAD

**Issue by cleder** [pytest-dev/pytest-cov#87]
py.test --cov=core --cov=twitter --cov-append twitter
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.8/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/config.py", line 32, in main
    config = _prepareconfig(args, plugins)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/config.py", line 85, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 393, in execute
    return wrapped_call(method(*args), self.execute)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 109, in wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 138, in get_result
    py.builtin._reraise(*ex)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 123, in __init__
    self.result = func()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/config.py", line 636, in pytest_cmdline_parse
    self.parse(args)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/config.py", line 746, in parse
    self._preparse(args)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/config.py", line 713, in _preparse
    self.pluginmanager.consider_setuptools_entrypoints()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/_pytest/core.py", line 278, in consider_setuptools_entrypoints
    plugin = ep.load()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/pkg_resources.py", line 2259, in load
    if require: self.require(env, installer)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/pkg_resources.py", line 2272, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (webassets 0.10.1 (/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages), Requirement.parse('webassets==0.10')) py.test --cov=core --cov=twitter --cov-append twitter returned exit code 1

**Comment by The-Compiler** [comment]
I don't see how this would be an issue with pytest-cov - I'm guessing it happens without `--cov` as well, no? `webassets` isn't used by `pytest-coverage` in any way.

**Comment by ionelmc** [comment]
Pytest's plugin loader uses setuptools entrypoints. You have some broken install of webassets and that confuses pkg_resources (part of setuptools). You should rebuild the virtualenv.

**Comment by ionelmc** [comment]
I think we can reasonably close this.
