### ISSUE TITLE
Calling subprocess fails (and outright crashes on python 2.6) when given a relative path for --cov-config

### ISSUE THREAD

**Issue by embray** [pytest-dev/pytest-cov#94]
As I documented over in astropy/astropy-helpers#193, if I specify a relative path to a coveragerc file with the `--cov-config` option, and then one of my tests changes to a different directory and starts a subprocess, then an exception occurs during processing of the pytest-cov.pth file:

```
Traceback (most recent call last):
  File "/home/embray/miniconda/envs/test/lib/python2.6/site.py", line 525, in <module>
    main()
  File "/home/embray/miniconda/envs/test/lib/python2.6/site.py", line 508, in main
    known_paths = addsitepackages(known_paths)
  File "/home/embray/miniconda/envs/test/lib/python2.6/site.py", line 288, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "home/embray/miniconda/envs/test/lib/python2.6/site.py", line 185, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/embray/miniconda/envs/test/lib/python2.6/site.py", line 155, in addpackage
    exec line
  File "<string>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "/home/embray/miniconda/envs/test/lib/python2.6/site-packages/pytest_cov/embed.py", line 58, in init
    auto_data=True)
  File "/home/embray/miniconda/envs/test/lib/python2.6/site-packages/coverage/control.py", line 138, in __init__
    "Couldn't read '%s' as a config file" % config_file
coverage.misc.CoverageException: Couldn't read 'astropy_helpers/tests/coveragerc' as a config file
```

This is because the relative path is written into the `COV_CORE_CONFIG` environment variable. So after changing directories that file cannot be found and we get a crash upon trying to process it.

On most Python versions this exception is ignored in site.py (so the coverage feature is still broken, but otherwise the tests pass).  On Python 2.6, however, the exception is not ignored and the tests fail too.

A simple workaround would be to always store the path to the config file as an absolute path.

**Comment by ionelmc** [comment]
Also: https://github.com/pytest-dev/pytest-cov/issues/77

**Comment by ionelmc** [comment]
Feel free to try https://github.com/pytest-dev/pytest-cov/pull/95
